### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by NasKhalil** [NasKhalil/capstone-project#21]
Hi Microverse team 👋 

Please find a below-attached link to our project:
`https://github.com/NasKhalil/capstone-project/projects/1`

We are a group of 2: @mohamedelshamy55 & @NasKhalil

**Comment by bimbolabuari** [comment]
Hi Team, 

You have done a good job so far 🚀  

## Highlights 🎉 

- Link to your GitHub project
- Information about the number of people in your  group

There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 



## Required Changes ♻️
- Let's assign all cards to team members in a fair way 👍 

Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

**Comment by NasKhalil** [comment]
Hi Microverse team 👋 

we've added the required changes:

- assign all cards to team members in a fair way 👌

**Comment by SajjadAhmad14** [comment]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi team, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
